#!/bin/zsh

current_dir="$(pwd)"
script_dir="$(dirname "$0")"
echo $script_dir/src/iup/runtime.c

if [ ! -f "$script_dir/src/iup/runtime.o" ]; then
    gcc -c -g -std=c99 "$script_dir/src/iup/runtime.c" -o "$script_dir/src/iup/runtime.o"
fi

source_file="$1"
asm_file="$current_dir/${source_file%.py}.s"
exe_file="$current_dir/${source_file%.py}"

# Compile the source file
python "$script_dir/main.py" "$source_file" -o "$exe_file"
